repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        exclude: package.lock.json
        args: ["--exclude-lines", "\\s*\"image/png\": \".+\""]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.2  # Use the latest version
    hooks:
      - id: ruff
        args: ["check", "--select", "I,F,B,A", "--fix"]
      - id: ruff-format
        args: ["--line-length", "120"]
